### ISSUE TITLE
Give us access to "Add sounds" to" Last Year Project " server

### ISSUE THREAD

**Issue by wah200** [Spudular/Chop-Chop#3]
please give us access on the discord server last Year project. to the soundboard add sound part

**Comment by wah200** [comment]
please give us access on the discord server last Year project. to the soundboard add sound part

**Comment by CW668** [comment]
Please could you add a description to this ticket.

**Comment by wah200** [comment]
reviewed - tested by added a Notifiaction

**Comment by wah200** [comment]
@
